### ISSUE TITLE
add data validation

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#35]
checklist:
- [x] Correct data file format
- [x] Correct column names
- [x] No empty observations
- [x] Missingness not beyond expected threshold
- [x] Correct data types in each column
- [x] No duplicate observations
- [x] No outlier or anomalous values
- [x] Correct category levels (i.e., no string mismatches or single values)
- [x] Target/response variable follows expected distribution
- [x] No anomalous correlations between target/response variable and features/explanatory variables
- [x] No anomalous correlations between features/explanatory variables
- [x] No data leakage between the training and test set

**Comment by fiaaatlux** [comment]
- [x]  Correct category levels (i.e., no string mismatches or single values)
- [x]  Target/response variable follows expected distribution
- [x]  No anomalous correlations between target/response variable and features/explanatory variables
- [x]  No anomalous correlations between features/explanatory variables
- [x]  No data leakage between the training and test set

Assigned to Alix(me)

**Comment by sgdkd** [comment]
- [x] Correct data file format
- [x]  Correct column names
- [x]  No empty observations
- [x]  Missingness not beyond expected threshold
- [x]  Correct data types in each column
- [x]  No duplicate observations
- [x]  No outlier or anomalous values
Assigned to sgdkd(me)

**Comment by sgdkd** [comment]
> * [x]   Correct category levels (i.e., no string mismatches or single values)
> * [x]   Target/response variable follows expected distribution
> * [x]   No anomalous correlations between target/response variable and features/explanatory variables
> * [x]   No anomalous correlations between features/explanatory variables
> * [x]   No data leakage between the training and test set
> 
> Assigned to Alix(me)

I can cover the first one in pandera part `"color": pa.Column(str, pa.Check.isin(["red", "white"])`

**Comment by fiaaatlux** [comment]
Done
