### ISSUE TITLE
Some concerns about git commit

### ISSUE THREAD

**Issue by fiaaatlux** [UBC-MDS/group-2#37]
Guys, I noticed there are over 60 commits for the Week 1 milestone. I think before we start our week 2 milestone, we need to clarify something this time. 

In a real-world working environment, maintaining a clean and organized Git commit history is crucial. Whenever an issue arises, a clear history is essential for rolling back changes effectively. Otherwise, locating the correct version to roll back to can be a complete disaster. And this is also a basic requirement in most company development guidelines. 

Every commit should have a clear and meaningful purpose, reflecting a logical unit of work. Minor edits, such as tweaking a single line or making small, isolated changes, should be grouped into larger commits whenever possible to keep the history clean and well-organized.

**Comment by Psingh238** [comment]
I will work toward making sure the Git commits are more detailed and not for trivial changes. Thank you for bringing up this concern.

**Comment by sgdkd** [comment]
Agreed! A clean and organized commit history is essential for collaboration and rollback efficiency. Let’s aim for meaningful, consolidated commits moving forward.

**Comment by fiaaatlux** [comment]
Thanks guys~
