### ISSUE TITLE
Conda-lock file does not capture pip dependencies

### ISSUE THREAD

**Issue by Psingh238** [UBC-MDS/group-2#42]
Pip packages are not being captured by conda-lock and therefore any packages listed in the pip section of `environment.yml` are not being loaded into the Docker image. We might need to contact Tiffany about this unless we can find a solution ourselves.

**Comment by Psingh238** [comment]
Looking around, I found the following [website](https://conda.github.io/conda-lock/pip/) and found this:

> We recommend avoiding the --kind=explicit flag when there are pip dependencies. Most tools (except for conda-lock install) do not recognize pip dependencies from explicit lockfiles, so they may be silently ignored. The default lockfile format explicitly supports pip dependencies.

However, I also found out that certain packages, like `ucimlrepo`, do exist in conda-forge so we should be able to move it from the pip section to the normal conda section.

**Comment by Psingh238** [comment]
Okay, I have found out that every package except `altair-ally` is available on conda-forge channel. Therefore, we can solve the issues for the other packages but we would need to take a deliberate action to probably install altair-ally in the Dockerfile commands instead. Let me know what you all think about this.

**Comment by musiccabin** [comment]
do you know how to do this: "install altair-ally in the Dockerfile commands"? i'm fine with it as long as it can make the docker image work. if you already know how to do it, you can just modify my branch and push it up again.

**Comment by Psingh238** [comment]
@musiccabin Yes, I think I have an idea on how to do that. I can make the change to your branch and push it.

**Comment by Psingh238** [comment]
@musiccabin I have made the requested change and pushed the branch. My Internet is being really finicky right now so I am unable to work on more things. The only thing left now is updating `environment.yml` to move the pip dependencies except altair-ally into the conda dependencies section.

**Comment by musiccabin** [comment]
ok i guess that's the last thing left for this milestone? i can work on it tmr if you need help, but you'll probably need to send me step-by-step instructions on what to do. (i merged your branch btw.)

**Comment by Psingh238** [comment]
@musiccabin I can make the change on your branch if you would like me to do that.

**Comment by musiccabin** [comment]
Yes please. Thx so much for helping me fix these!
