### ISSUE TITLE
create release 1.0.0

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#43]
@sgdkd @Psingh238 @fiaaatlux hey all, are you good with me creating a release if repo looks good? i can submit to gradescope after as well.

**Comment by Psingh238** [comment]
I am fine with that. I just confirmed that the GitHub actions are working as well.

**Comment by musiccabin** [comment]
thank you!
release (1.0.0) and gradescope submission made.
[522 Milestone 2 Group 2.pdf](https://github.com/user-attachments/files/17963724/522.Milestone.2.Group.2.pdf)

have a great weekend!
