### ISSUE TITLE
script 1: download_data

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#45]
downloads the data from the internet and saves it locally. This should take at least two arguments:

- the path to the input file (a URL or a relative local path, such as data/file.csv), as well as
- a path/filename where to write the file to and what to call it (e.g., data/cleaned_data.csv).

**Comment by Psingh238** [comment]
Due to using the UCI ML repo dataset, the data is coming from the python package we are already installing. Therefore, the first argument would need to be an ID that UCI uses for their datasets instead. I will make this change when I work on this after the update to `environment.yml`.
