### ISSUE TITLE
Rename repository name

### ISSUE THREAD

**Issue by Psingh238** [UBC-MDS/group-2#5]
Hello everyone, since we have decided on the dataset, we should change the repository name to reflect that. I was personally thinking of `wine-quality-regressor` as the name but I would like to know about other suggestions.

**Comment by sgdkd** [comment]
I think `wine-quality-regressor` is fine.

**Comment by fiaaatlux** [comment]
maybe also include our group number?

**Comment by Psingh238** [comment]
Of course, although, I would recommend to do this at the end so that it does not interfere with the current locally cloned git repositories since changing the name would require adjusting the upstream branch.

**Comment by Psingh238** [comment]
Since it's Saturday, I will update the repository name now.
