### ISSUE TITLE
update README about scripts

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#50]
example: https://github.com/ttimbers/breast-cancer-predictor/blob/2.0.0/README.md

**Comment by musiccabin** [comment]
@sgdkd pls pull my branch for latest code for model_and_result.py. i can update this tmr too - if you need help, pls lmk. should be very quick.

**Comment by sgdkd** [comment]
> @sgdkd pls pull my branch for latest code for model_and_result.py. i can update this tmr too - if you need help, pls lmk. should be very quick.@sgdkd请拉取我的分支以获取model_and_result.py的最新代码。我也可以更新这个 TMR - 如果你需要帮助，请 LMK。应该非常快。

Hi, the README is updated but scripts path need update, pls see #63 #65
