### ISSUE TITLE
update computational env

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#52]
At a minimum, you will be adding Quarto as a new dependency to your project.

- [ ] update environment.yml with versions pinned
- [ ] rebuild docker container image and publish to DockerHub
- [ ] update documentation accordingly

**Comment by musiccabin** [comment]
@Psingh238 pls do this one first as i realized stuff like testing the rendered pdf/html report depend on this. tysm!

**Comment by Psingh238** [comment]
I will work on this during the lab then.
