### ISSUE TITLE
test quarto report generation (pdf or html)

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#61]
could you pls help me test generating the report using the instructions here: https://github.com/UBC-MDS/dsci-522-individual-assignment-quarto-python/blob/main/README.md?

whenever i run docker, my computer runs out of space and doesn't let me proceed on `docker compose up`. tysm for your help!

**Comment by Psingh238** [comment]
I followed the instructions but there are some errors in the qmd and I am correcting them right now. WE also need to update the Dockerfile to have a couple more commands to download the package to render to pdf.

**Comment by Psingh238** [comment]
I will also make the changes you requested regarding the .gitignore as well.

**Comment by Psingh238** [comment]
The HTML does render correctly but the citations are somewhat off and the links to the images aren't working quite right. But I think we can fix that.

**Comment by Psingh238** [comment]
The rendering was tested and any issues have been fixed now and you can see in the latest commits by me to #54. I will therefore close this Issue since it has been resolved.
