### ISSUE TITLE
eda fn + test

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#72]
- function lives in an .py file in a sub-directory called `src`: `import` functions to scripts
- tests live in `test` folder: use pytest

**Comment by fiaaatlux** [comment]
create_quality_distribution_plot,
    create_wine_quality_proportion_plot,
    create_sulfur_dioxide_scatter,
    create_correlation_matrix,
    create_boxplots_by_color,
    create_quality_distribution_bar
