### ISSUE TITLE
write_data.py + test

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#74]
- function lives in an .py file in a sub-directory called `src`: `import` functions to scripts
- tests live in `test` folder: use pytest

**Comment by Psingh238** [comment]
The function being written is `write_data` which takes in Pandas DataFrames and writes them out to CSVs.

**Comment by musiccabin** [comment]
closing this as the function has already been made by @sgdkd in `src/data_validation.py`
