### ISSUE TITLE
update `CHANGELOG.md`

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#75]
include evidence of addressing peer review and instructor feedback:
- by providing URLs to reference specific lines of code, commit messages, pull requests, etc.
- add some narration and explanation to changes made
- if no changes are made clarify reasoning behind

link to peer review: https://github.com/UBC-MDS/data-analysis-review-2024/issues/25
**addressing feedback and peer review issues counts 50-75% of grade for this milestone**

**Comment by musiccabin** [comment]
sorry guys i accidentally pushed to main just now because i thought i created a branch but i didn't, but anyway, thankfully it's not a big trouble since i was just updating CHANGELOG.md in that branch... 

i'm done for my part for this milestone but i'll be available to help debugging / testing, as i haven't tested makefile to ensure scripts all run smoothly. i'll try to make space on my laptop now that i can remove 573 and 513 course envs.

<img width="558" alt="Screenshot 2024-12-13 at 9 55 57 PM" src="https://github.com/user-attachments/assets/b17c8b42-021a-4457-9b6b-fd585ab89b1e" />

**Comment by sgdkd** [comment]
Added #84 #80 in CHANGELOG
