### ISSUE TITLE
peer review: save model

### ISSUE THREAD

**Issue by musiccabin** [UBC-MDS/group-2#87]
It was noted the final model/pipeline was not being saved to results after tuning the hyperparameters. I think it could be useful to save this model, if a future collaborator wants to explore the performance of your existing model further on more unseen data. This also helps with transparency and reproducibility!

**Comment by musiccabin** [comment]
pls decide if we'll address this issue: if not, pls mention the reason why (i.e. we are not calling it in our scripts or Makefile, so there's no apparent added value in saving it) and feel free to close it. ty! @Psingh238

**Comment by Psingh238** [comment]
I believe we can address it by simply doing a pickle dump of the model after the hyperparameter optimization and let the end user decide if they would like to use the optimized version to test against other models or not.

**Comment by musiccabin** [comment]
Even tho I don't see a clear reason, I'm okay with it, since it addresses the peer reviewer's issue. You can feel free to go ahead and do it. I'm not by my computer but I should get access in half an hour ish and I'll reply to other things including pr's then. :)

**Comment by Psingh238** [comment]
Alright, I will implement this using a pickle dump of the model then.
